import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', ...defaultTheme.fontFamily.sans],
                "body-lg": ["Inter"],
                "label-md": ["Inter"],
                "label-sm": ["Inter"],
                "headline-md": ["Inter"],
                "headline-lg-mobile": ["Inter"],
                "body-md": ["Inter"],
                "headline-xl": ["Inter"],
                "body-sm": ["Inter"],
                "headline-lg": ["Inter"],
                headline: ['Plus Jakarta Sans', 'sans-serif'],
                display: ['Plus Jakarta Sans', 'sans-serif'],
                body: ['Inter', 'sans-serif'],
            },
            colors: {
                "tertiary": "#1e1200",
                "primary-container": "#1e293b",
                "surface-container": "#eceef0",
                "surface-tint": "#545f73",
                "on-primary-fixed": "#111c2d",
                "surface-dim": "#d8dadc",
                "on-secondary-fixed": "#07006c",
                "primary-fixed-dim": "#bcc7de",
                "on-error": "#ffffff",
                "on-tertiary-fixed": "#271902",
                "surface-container-low": "#f2f4f6",
                "inverse-on-surface": "#eff1f3",
                "inverse-primary": "#bcc7de",
                "on-primary-container": "#8590a6",
                "surface-variant": "#e0e3e5",
                "surface": "#f7f9fb",
                "secondary": "#4648d4",
                "secondary-fixed-dim": "#c0c1ff",
                "outline": "#75777d",
                "on-surface": "#191c1e",
                "surface-container-lowest": "#ffffff",
                "error-container": "#ffdad6",
                "on-surface-variant": "#45474c",
                "surface-bright": "#f7f9fb",
                "inverse-surface": "#2d3133",
                "outline-variant": "#c5c6cd",
                "on-tertiary": "#ffffff",
                "secondary-fixed": "#e1e0ff",
                "on-error-container": "#93000a",
                "on-secondary": "#ffffff",
                "tertiary-container": "#35260c",
                "on-primary": "#ffffff",
                "primary": "#091426",
                "secondary-container": "#6063ee",
                "error": "#ba1a1a",
                "surface-container-highest": "#e0e3e5",
                "on-tertiary-fixed-variant": "#564427",
                "on-secondary-fixed-variant": "#2f2ebe",
                "background": "#f7f9fb",
                "surface-container-high": "#e6e8ea",
                "tertiary-fixed": "#fadfb8",
                "on-tertiary-container": "#a38c6a",
                "on-secondary-container": "#fffbff",
                "on-primary-fixed-variant": "#3c475a",
                "tertiary-fixed-dim": "#ddc39d",
                "on-background": "#191c1e",
                "primary-fixed": "#d8e3fb",
                
                brand: {
                    50: '#f5f3ff',
                    100: '#ede9fe',
                    200: '#ddd6fe',
                    700: '#6d28d9',
                    800: '#5b21b6',
                    900: '#4c1d95',
    },
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "stack-sm": "8px",
                "stack-lg": "24px",
                "gutter": "24px",
                "container-max": "1440px",
                "stack-md": "16px",
                "margin-x": "32px"
            },
            fontSize: {
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
                "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "headline-xl": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
                "headline-lg": ["30px", {"lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "600"}]
            }
        },
    },

    plugins: [forms],
};
